GET http://127.0.0.1/pass HTTP/1.1
Cookie: jwt_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhbmRvbSIsImlhdCI6MTYyOTUzMTAyOSwiZXhwIjoxNjI5NTMxMDg5fQ.MX0FGhUuXxGhqi_xvxMW7kt5Uy2PaLGphcdXuUSruUo

